# set the default docker image
image: registry.gitlab.com/tjvb/phpimages:php81

stages:
  - prepare # prepare the cache
  - check # check the codestyles
  - test

prepare_cache:
  stage: prepare
  interruptible: true
  script:
    # Install composer
    - composer validate
    - composer install
  # we use this artifact for all the jobs
  artifacts:
    name: "vendor"
    paths:
      - vendor/*

lint:
  stage: check
  script:
    # lint recursive
    - find src/ -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  dependencies: []
  needs: []

phpcs:
  stage: check
  interruptible: true
  script:
    - vendor/bin/phpcs
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

phpmd:
  image: phpqa/phpmd
  interruptible: true
  stage: check
  script:
    - phpmd src/ text phpmd.xml.dist
  dependencies: []
  needs: []

phpstan:
  stage: check
  interruptible: true
  script:
    # check for phpstan errors
    - php -d memory_limit=500M vendor/bin/phpstan analyse --error-format=gitlab > phpstan.json
    - cat phpstan.json
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache
  artifacts:
    paths:
      - phpstan.json
    when: always

# this is a template that we reuse for the different test jobs
.test_base:
  stage: test
  interruptible: true
  coverage:  '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    reports:
      junit: phpunitresult/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: phpunitresult/cobertura-coverage.xml
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache

test_lowest:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    # Install composer
    - rm -f composer.lock
    - composer update --prefer-lowest
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml


test_php80_laravel_8:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    - composer require --dev orchestra/testbench=^6.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml

test_php80_laravel_9:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php80
  script:
    - composer require --dev orchestra/testbench=^7.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml

test_php81_laravel_8:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php81
  script:
    - composer require --dev orchestra/testbench=^6.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml

test_php81_laravel_9:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php81
  script:
    - composer require --dev orchestra/testbench=^7.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml

test_php82_laravel_8:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php82
  script:
    - composer require --dev orchestra/testbench=^6.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml

test_php82_laravel_9:
  extends: .test_base
  image: registry.gitlab.com/tjvb/phpimages:php82
  script:
    - composer require --dev orchestra/testbench=^7.0
    - vendor/bin/phpunit --coverage-text --colors=never --coverage-cobertura=phpunitresult/cobertura-coverage.xml --log-junit=phpunitresult/junit.xml
    - sed -i 's~ filename="~ filename="src/~' phpunitresult/cobertura-coverage.xml
    
infection:
  stage: test
  interruptible: true
  script:
    - composer install
    - vendor/bin/infection
  artifacts:
    name: "Infection result ${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"
    when: always
    paths:
      - build/infection/infection.log
      - build/infection/infection-summary.log
      - build/infection/infection-log.json
      - build/infection/infection-per-mutator.md
    expire_in: 1 day
    expose_as: Infection log
  dependencies:
    - prepare_cache
  needs:
    - prepare_cache
